### ISSUE TITLE
vswhere hangs (2020 edition)

### ISSUE THREAD

**Issue by timmkrause** [microsoft/vswhere#211] opened 2020-02-14 12:09 UTC
Obviously I would have to accept the "not supported" card, but I will try it anyway...

We want to run build agents within Docker containers for Azure Pipelines containing Visual Studio 2019 Community (because the Build Tools are missing some important SSDT components to actually build database projects and the only variant to get SSDT with all necessary components in this regard is via Visual Studio, see [here](https://techcommunity.microsoft.com/t5/sql-server-integration-services/new-delivery-model-for-sql-server-data-tools-in-visual-studio/bc-p/963770/highlight/true#M578) and [here](https://stackoverflow.com/a/60148153/824483)).

I have built the image **locally** (Windows 10, 1903, Docker Desktop Community) using [this Dockerfile](https://github.com/lukas-lansky/visual-studio-docker-build/blob/master/vs.Dockerfile) and added the [agent installation process](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops) on top of it.

It works perfect when running the container locally.

Saved the image and loaded it into the Docker host (which is a Hyper-V VM running Windows Server 2019 Core/without desktop and Docker Enterprise [as the docs recommend](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops#install-docker-for-windows)).

Starting the container here results in hanging of `vswhere.exe`:

```
[2020-02-14 10:09:21Z INFO PowerShellCapabilitiesProvider] STDOUT: Getting latest Visual Studio 15 setup instance.
[2020-02-14 10:09:21Z INFO PowerShellCapabilitiesProvider] STDOUT: & C:\azp\agent\bin\powershell\CapabilityHelpers\..\..\..\externals\vswhere\vswhere.exe -version '[15.0,16.0)' -latest -format json
```

**Comment by heaths** [comment] 2020-02-14 16:12
I doubt it's hanging: you specified 15.x only, which is Visual Studio 2017. If you installed 2019, you wouldn't get any output. Try just -latest without -version and see if that works better for you. Since you know what you installed in the box, you could even skip vswhere entirely since you know where VS would be installed (and can even set a different location during install).

If after those notifications it still doesn't work, we'd need a dump to investigate this issue further.

**Comment by timmkrause** [comment] 2020-02-14 18:24
I am not running this on my own. It‘s done by the Azure Pipelines Agents config.cmd step where it scans for its capabilities.
And this step ist not exiting.

**Comment by heaths** [comment] 2020-02-14 18:42
You'd have to install and set up Remote Tools, which contains the remote debugger. But if the agent has 2019 on it, this command will never return a match for the reason I stated. Is this a hosted image? Which one?

**Comment by heaths** [comment] 2020-02-15 16:40
Digging into this more, I found https://github.com/microsoft/azure-pipelines-agent/issues/2004 which not only exhibits the same problem, but also indicates you may have an older agent that does overly and unnecessarily constrict the search for the latest VS. Could you try redownloading a more recent agent?

That said, they are also using an older version that has a potential [deadlock issue](https://github.com/microsoft/vswhere/issues/87) from the CRT. I'll file a bug on them to update. But do try a newer agent. Even if it isn't deadlocking, you won't find VS2019 with a `-version [15.0,16.)` filter which they seemed to have removed.

**Comment by timmkrause** [comment] 2020-02-15 17:16
Have you checked the script of

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops

This approach always downloads the latest releases of the agent installer.
It may be the case that the statement wouldn‘t find VS2019.
But my assumption is that the scanning scripts execute multiple calls against vswhere.
And it is a fact that when I run the agent installation process on my machine (within the Docker container during startup) it detects VS2019 as a capability.

**Comment by heaths** [comment] 2020-02-15 17:39
The host machine shouldn't make a difference since the system files are contained within the container image. Kernel address spare shouldn't be shared either unless you're using process isolation instead of Hyper-V isolation, which is all Windows 10 is capable of. If nested hypervisors is configured (I imagine it probably is if you're running docker in a VM), try passing `--isolation hyperv` and see if the issue repros.

Just out of curiosity, though: why run containers in a VM instead of increasing container density on the bare metal host?

**Comment by timmkrause** [comment] 2020-02-15 18:05
Will try that, thank you for your insights.

Regarding your question: We hoped for a quick solution this way. Running it on bare metal would bring even more problems for us which are related to the IT department... IPs, firewalls, proxies and other policies.

**Comment by heaths** [comment] 2020-02-15 18:20
I see. Thanks for sharing.

One other thing you might try, if you can replace vswhere.exe in the externals directory with the latest version of vswhere.exe - assuming it doesn't get replaced - it might fix the problem. The known deadlock issue (loader lock caused by older versions of the CRT) was fixed in 2.1.3, though it still occurred - more rarely - in older versions of VS2017 but was, IIRC, fixed in 15.3 (VS2017 Update 3). Since you're trying to use VS2019 that issue should not exist in VS, but still can happen with vswhere.exe 1.0.62 they are using.

I'm going to try to submit a PR against their repo to update the version.

**Comment by timmkrause** [comment] 2020-02-17 06:43
So what I will try this week is to replace all occurrences of `vswhere.exe` (dunno if there are multiple) on the fly in the container with this version:

https://github.com/microsoft/vswhere/releases/download/2.8.4/vswhere.exe

Will get back as soon as I have tried it.

Thanks again!

**Comment by timmkrause** [comment] 2020-02-20 12:45
Using 2.8.4 did not help.

But using `--isolation=hyperv` did it! I am sorry for the false alarm within your repo, but obviously I just got in contact with the right person to solve this problem.

I will open source the dockerized Azure Pipelines Agent as a sign of gratitude.

Thank you so much for your passion.

**Comment by heaths** [comment] 2020-02-20 18:07
Glad to hear it. That is unfortunate since process isolation should be at least a little faster. Were you using the latest container image? It's odd they are still using an older VC runtime that has the locale deadlock issue that forced me to take a new version in both vswhere as well as the COM server that VS ships/installs.

Since the issue is "resolved", I'm closing this bug. But I'd love to hear if you are ever able to use process isolation without the deadlock.

**Closed by heaths** 2020-02-20 18:07 UTC
Labels: external, need-repro
